# Site
name: "Memoirs"
title: "Memoirs"
description: "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/website'
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: wowthemesnet@gmail.com

# Authors
authors:
 
# Authors
authors:
  sreya:
    name: Sreya Nalla
    display_name: Sreya
    avatar: 'assets/images/bv-images/sreya-avatar.png'
    email: sreyanalla@gwu.edu
    web: https://www.sreyanalla.com
    twitter: https://github.com/sreyanalla
    description: "A 21-year old interested in the intersection of computer science and other disciplines."

  christina:
    name: Christina Ng
    display_name: Christina    
    avatar: 'assets/images/bv-images/christina-avatar.png'
    email: christina_ng@gwu.edu
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."
  
  melody:
    name: Melody Lee
    display_name: Melody    
    avatar: 'assets/images/bv-images/melody-avatar.png'
    email: melodylee@gwu.edu
    web: https://www.wowthemes.net
    twitter: https://github.com/
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."
  
  linnea:
    name: Linnea Dierksheide
    display_name: Linnea    
    avatar: 'assets/images/bv-images/linnea-avatar.png'
    email: ldierksheide@gwu.edu
    web: https://www.wowthemes.net
    twitter: https://github.com/
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
